### ISSUE TITLE
[Instruction Unclear] Got banned from Reddit

### ISSUE THREAD

**Issue by xx1182** [majestrate/bitchan#2]
Hi, i was trying to set up the imageboard, everything worked locally, and non-locally, but when i reach this:

add the bootstrap node (from your server server):

$ curl http://i2p.rocks:8800/bitchan/v1/peer-with-me?host=your.domain.tld

I don't know if it works, or not, because i got banned from reddit for calling a woman an n-word

**Comment by majestrate** [comment]
On Tue, 17 May 2022 03:29:46 -0700
xx1182 ***@***.***> wrote:

> Hi, i was trying to set up the imageboard, everything worked locally,
> and non-locally, but when i reach this:
> 
> add the bootstrap node (from your server server):
> 
> $ curl
> http://i2p.rocks:8800/bitchan/v1/peer-with-me?host=your.domain.tld
> 
> I don't know if it works, or not, because i got banned from reddit
> for calling a woman an n-word
> 

that server does not run bitchan anymore so peering with it will do
nothing. try doing so with another server.

**Comment by xx1182** [comment]
It is unclear who am I supposed to pair to? And what does pairing do, see the posts from other instances?

Regards.

**Comment by majestrate** [comment]
On Tue, 17 May 2022 04:24:40 -0700
xx1182 ***@***.***> wrote:

> It is unclear who am I supposed to pair to? And what does pairing do,
> see the posts from other instances?
> 
> Regards.
> 

pairing is the process of having two servers syndicate posts between
them going forward. this is an inactive project, if you want other
servers, you will have to figure that out on your own. glhf.

**Comment by xx1182** [comment]
> On Tue, 17 May 2022 04:24:40 -0700 xx1182 ***@***.***> wrote: It is unclear who am I supposed to pair to? And what does pairing do, see the posts from other instances? Regards.
> pairing is the process of having two servers syndicate posts between them going forward. this is an inactive project, if you want other servers, you will have to figure that out on your own. glhf.

Sorry but, why it's so complicated? Wouldn't be easier to just use gotemplates with protocols? What's all this shit, you're telling me this is coding??? 
From the perspective of imageboards abstracting, why don't just use the BitTorrent library and then memes???

**Comment by majestrate** [comment]
On Tue, 17 May 2022 07:16:20 -0700
xx1182 ***@***.***> wrote:

> > On Tue, 17 May 2022 04:24:40 -0700 xx1182 ***@***.***> wrote: It is
> > unclear who am I supposed to pair to? And what does pairing do, see
> > the posts from other instances? Regards. pairing is the process of
> > having two servers syndicate posts between them going forward. this
> > is an inactive project, if you want other servers, you will have to
> > figure that out on your own. glhf.
> 
> Sorry but, why it's so complicated? Wouldn't be easier to just use
> gotemplates with protocols? What's all this shit, you're telling me
> this is coding??? From the perspective of imageboards abstracting,
> why don't just use the BitTorrent library and then memes???
> 

we do use bittorrent, for serving post data between servers, propagating
the existence of new posts is not done via bittorrent as there are no
standards for such and i did not want to screw around in the bittorrent
library i was using to hack in an nih solution only i cared about.

if you check the last commit in this repo you can see when the last
activity in development was at. this project is inactive on my end, if
you wish to develop it, patches welcome.

**Comment by xx1182** [comment]
> 

Sorry, but can you explain the BitTorrent part better? A server must connect to a network, like the instructions suggest, then? Serving post data between servers? What does that mean? When a server goes down there is a copy on the "network"? But no communication implemented?

**Comment by majestrate** [comment]
On Tue, 17 May 2022 09:37:07 -0700
xx1182 ***@***.***> wrote:

> > 
> 
> Sorry, but can you explain the BitTorrent part better? A server must
> connect to a network, like the instructions suggest, then? Serving
> post data between servers? What does that mean? When a server goes
> down there is a copy on the "network"? But no communication
> implemented?
> 

when a server goes down all of its peers should have a copy of all post
content they finished fetching. the notification mechanism to tell
other servers "i have a new post, download it via bittorrent" is done
outside of bittorrent as there is no standard way to do it in
bittorrent right now.

**Comment by xx1182** [comment]
> On Tue, 17 May 2022 09:37:07 -0700 xx1182 ***@***.***> wrote: > Sorry, but can you explain the BitTorrent part better? A server must connect to a network, like the instructions suggest, then? Serving post data between servers? What does that mean? When a server goes down there is a copy on the "network"? But no communication implemented?
> when a server goes down all of its peers should have a copy of all post content they finished fetching. the notification mechanism to tell other servers "i have a new post, download it via bittorrent" is done outside of bittorrent as there is no standard way to do it in bittorrent right now.

Can't you just make a timer to refresh the index everytime? Since it's servers, maybe servers could have
{
 torrentdate: date
} 

And since peers are connected just make a downloadable .torrent file so it's cool and, can you send me the torrent?
